//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWWORK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proje1Entities : DbContext
    {
        public Proje1Entities()
            : base("name=Proje1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Günlük_iş> Tbl_Günlük_iş { get; set; }
        public virtual DbSet<Tbl_iş_aktivite> Tbl_iş_aktivite { get; set; }
        public virtual DbSet<Tbl_iş_Durumu> Tbl_iş_Durumu { get; set; }
        public virtual DbSet<Tbl_Kategori> Tbl_Kategori { get; set; }
        public virtual DbSet<Tbl_Kullanici> Tbl_Kullanici { get; set; }
        public virtual DbSet<Tbl_iş_işlem> Tbl_iş_işlem { get; set; }
    }
}
