//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_iş_Durumu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_iş_Durumu()
        {
            this.Tbl_Günlük_iş = new HashSet<Tbl_Günlük_iş>();
        }
    
        public int iş_Durum_ID { get; set; }
        public string iş_onay_durumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Günlük_iş> Tbl_Günlük_iş { get; set; }
    }
}
