//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_iş_işlem
    {
        public int Kullanici_ID { get; set; }
        public int iş_ID { get; set; }
        public string işlem { get; set; }
    
        public virtual Tbl_Günlük_iş Tbl_Günlük_iş { get; set; }
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
    }
}
